### ISSUE TITLE
Using a different font size for header and body cells makes can break “em” based column widths

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#1000]
If a theme uses different font sizes for `[part~="header-cell]` than for body cells, using `<vaadin-grid-column width="10em">` makes the column widths be out of sync.

A workaround is to set the font size for the slotted element inside the header cell instead:

```css
[part~="header-cell"] ::slotted(*) {
  font-size: 12px;
}
```
