### ISSUE TITLE
There's an ugly focus outline on grid in Firefox

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-grid#1217]
![peek 2018-02-09 11-18](https://user-images.githubusercontent.com/6059356/36020369-1cda4a78-0d8b-11e8-95a7-9d61ad76eead.gif)

`outline: none` isn't enough for Firefox, this should help:

```css
&::-moz-focus-inner {
  border: 0;
}
```
