### ISSUE TITLE
<vaadin-grid-selection-column> - checkbox rendering issue

### ISSUE THREAD

**Issue by silvan-lincan** [vaadin/vaadin-grid#1561]
### Description
Vaadin 13.0.0.beta1
Vaadin Flow Server Version: 1.3.0
vaadin-grid-5.3.0

In a Vaadin Grid with selection set to MULTI, checkboxes from the `<vaadin-grid-selection-column>` are rendered with "three dots".

### Expected outcome
![image](https://user-images.githubusercontent.com/47028355/52573280-14881200-2e1a-11e9-84c8-575c09403f8e.png)

### Actual outcome
![image](https://user-images.githubusercontent.com/47028355/52573100-aa6f6d00-2e19-11e9-9b93-11949fc94fd2.png)

### Steps to reproduce
1. Put a `vaadin-grid` element in a page.
2. Set selection mode to multi: `grid.setSelectionMode(Grid.SelectionMode.MULTI);`
3. Open the page in a web browser.

Please see an example attached.
[demo-grid.zip](https://github.com/vaadin/vaadin-grid/files/2851747/demo-grid.zip)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by silvan-lincan** [comment]
After some investigation, it seems that the issue is coming from: vaadin-grid-styles.html
```css
[part~="cell"] ::slotted(vaadin-grid-cell-content) {
        display: block;
        width: 100%;
        box-sizing: border-box;
        overflow: hidden;
        text-overflow: ellipsis;
      }
```
line: `text-overflow: ellipsis;`
My suspicion is that, it shouldn't be there at all, or at least, if it is changed to: `text-overflow: clip;`, then the checkboxes are rendered Ok.

In vaadin-grid-5.2.8, the: `text-overflow` is not there at all.
