### ISSUE TITLE
Loading css rule causes stuttering

### ISSUE THREAD

**Issue by Avocher** [vaadin/vaadin-grid#1700]
### Description
The following css rules causes stuttering for us while while scrolling. It adds up to 60ms of `recalculating style`:
```css
[part~="row"][loading] [part~="body-cell"] ::slotted(vaadin-grid-cell-content) {
  opacity: 0;
}
```
Removing the rule fixes it for us but it might not work UX wise for everyone.

### Steps to reproduce
1. Scroll around in a larger grid

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome
