### ISSUE TITLE
Column text-align

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#193]
Provide text alignment (left/center/right) out of the box for columns.

E.g.

``` html
 <col align="right">
```

In the meantime, do the following:

``` html
<vaadin-grid>
  <col name="foobar">
  ...
</vaadin-grid>
```

``` javascript
grid.cellClassGenerator = function(cell) {
    return cell.columnName;
};
```

``` css
vaadin-grid .foobar {
  /* Cell elements are flex containers, and contain a span element by default which we can align */
  justify-content: flex-end;
  /* Add any necessary vendor prefixed properties as well */
}
```
