### ISSUE TITLE
Over-generic class names used in the column hiding dropdown menu

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#197]
At least the `.hidden` class used inside the dropdown is sure to clash with a very large amount of existing CSS in the wild. All the class names inside the grid local DOM should be prefixed with `vaadin-grid-`.

As a workaround, if you get affected by this issue, add the following CSS to your styles:

``` css
.vaadin-grid-sidebar .hidden {
  display: block !important;
}
```
