### ISSUE TITLE
Text selection for copy/paste actions?

### ISSUE THREAD

**Issue by cpboyd** [vaadin/vaadin-grid#316]
From David Mulder's paper-datatable, it's possible to click and drag to select text without selecting the row/item.
You can even select text across multiple rows.

It'd be nice if vaadin-grid offered similar functionality, as I'm using it to display information that users might want to copy.

Example:
http://david-mulder.github.io/paper-datatable/components/paper-datatable/demo/paper-datatable-card/full-implementation.html

**Comment by Saulis** [comment]
As a workaround, you should be able to override the styles with:

```css
vaadin-grid {
  -moz-user-select: text;
  -webkit-user-select: text;
  -ms-user-select: text;
}
```
