### ISSUE TITLE
svg files are required and duplicate iron-icons

### ISSUE THREAD

**Issue by cpboyd** [vaadin/vaadin-grid#323]
I've Vulcanized my Polymer website and noticed that vaadin-grid references the bower_components/vaadin-grid/img/ svg files.

Since these seem to be duplicates of similar icons in iron-icons, is there any objection to simply importing "../iron-icons/iron-icons.html" with the vaadin-grid element?

I'd imagine that most Polymer-based pages will likely be including that any way.

If there's concerns about overhead in loading additional icons that aren't used, have you considered possibly using `<svg>` built-in to the vaadin-grid element rather than a discrete SVG file?

**Comment by jounik** [comment]
Thanks for the feedback!

Since there are only a couple of icons, I would lean on the side of inlining the SVGs to vaadin-grid.html, rather than requiring everyone to import all iron-icons. This option has come up, but it hasn’t been any priority yet. I think we want to optimize the overall JS size first (#190).

**Comment by jahglow** [comment]
Please, do replace the svgs with the inline icons! They are totally messed up (missing) when vulcanizing the project! The code uses base64 of your icons, just lookupthe classes and replace line by line. I flagged them important to override the original styles but that one can be omitted.

```css 
     .vaadin-grid-header .sort-desc:after {
        content: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PHN2ZyB3aWR0aD0iMTJweCIgaGVpZ2h0PSIxMnB4IiB2aWV3Qm94PSIwIDAgMTIgMTIiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeG1sbnM6c2tldGNoPSJodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2gvbnMiPiAgICAgICAgPHRpdGxlPlNoYXBlPC90aXRsZT4gICAgPGRlc2M+Q3JlYXRlZCB3aXRoIFNrZXRjaC48L2Rlc2M+ICAgIDxkZWZzPjwvZGVmcz4gICAgPGcgaWQ9IlBhZ2UtMSIgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCIgc2tldGNoOnR5cGU9Ik1TUGFnZSI+ICAgICAgICA8cGF0aCBkPSJNNSwzLjggTDUsMTIgTDcsMTIgTDcsMy44IEwxMC41LDcuNCBMMTEuOSw1LjkgTDYsMCBMMCw1LjkgTDEuNCw3LjQgTDUsMy44IFoiIGlkPSJTaGFwZSIgZmlsbC1vcGFjaXR5PSIwLjg3IiBmaWxsPSIjMDAwMDAwIiBza2V0Y2g6dHlwZT0iTVNTaGFwZUdyb3VwIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSg1Ljk1MDAwMCwgNi4wMDAwMDApIHNjYWxlKDEsIC0xKSB0cmFuc2xhdGUoLTUuOTUwMDAwLCAtNi4wMDAwMDApICI+PC9wYXRoPiAgICA8L2c+PC9zdmc+) !important;
      }
      .vaadin-grid-header .sort-asc:after {
        content: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+PHN2ZyB3aWR0aD0iMTJweCIgaGVpZ2h0PSIxMnB4IiB2aWV3Qm94PSIwIDAgMTIgMTIiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeG1sbnM6c2tldGNoPSJodHRwOi8vd3d3LmJvaGVtaWFuY29kaW5nLmNvbS9za2V0Y2gvbnMiPiAgICAgICAgPHRpdGxlPlNoYXBlPC90aXRsZT4gICAgPGRlc2M+Q3JlYXRlZCB3aXRoIFNrZXRjaC48L2Rlc2M+ICAgIDxkZWZzPjwvZGVmcz4gICAgPGcgaWQ9IlBhZ2UtMSIgc3Ryb2tlPSJub25lIiBzdHJva2Utd2lkdGg9IjEiIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCIgc2tldGNoOnR5cGU9Ik1TUGFnZSI+ICAgICAgICA8cGF0aCBkPSJNNSwzLjggTDUsMTIgTDcsMTIgTDcsMy44IEwxMC41LDcuNCBMMTEuOSw1LjkgTDYsMCBMMCw1LjkgTDEuNCw3LjQgTDUsMy44IFoiIGlkPSJTaGFwZSIgZmlsbC1vcGFjaXR5PSIwLjg3IiBmaWxsPSIjMDAwMDAwIiBza2V0Y2g6dHlwZT0iTVNTaGFwZUdyb3VwIj48L3BhdGg+ICAgIDwvZz48L3N2Zz4=) !important;
      }
      input[type="checkbox"] + label:after {
        content: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTZweCIgaGVpZ2h0PSIxNnB4IiB2aWV3Qm94PSIwIDAgMTYgMTYiIHZlcnNpb249IjEuMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4zMDEyODMyOCw4LjY2MzI1NTM5IEw1Ljk2ODk0OTUyLDEyLjI0NTM5ODcgQzYuMzYwNzYxNiwxMi42MjgwNzQ0IDYuOTg3NTAyMTUsMTIuNjI0Mzc3OSA3LjM3NDc3MzAyLDEyLjIzNzEwNyBMMTMuOTA0NzczMiw1LjcwNzEwNjc4IEMxNC4yOTUyOTc1LDUuMzE2NTgyNDkgMTQuMjk1Mjk3NSw0LjY4MzQxNzUxIDEzLjkwNDc3MzIsNC4yOTI4OTMyMiBDMTMuNTE0MjQ4OSwzLjkwMjM2ODkzIDEyLjg4MTA4NCwzLjkwMjM2ODkzIDEyLjQ5MDU1OTcsNC4yOTI4OTMyMiBMNS45NjA1NTk0NiwxMC44MjI4OTM0IEw3LjM2NjM4Mjk2LDEwLjgxNDYwMTggTDMuNjk4NzE2NzIsNy4yMzI0NTg1IEMzLjMwMzYxMzA3LDYuODQ2NTY3OTEgMi42NzA0OTIxNCw2Ljg1NDAzNjU3IDIuMjg0NjAxNTUsNy4yNDkxNDAyMiBDMS44OTg3MTA5Niw3LjY0NDI0Mzg4IDEuOTA2MTc5NjIsOC4yNzczNjQ4IDIuMzAxMjgzMjgsOC42NjMyNTUzOSBMMi4zMDEyODMyOCw4LjY2MzI1NTM5IFoiIGZpbGw9IiNmZmZmZmYiPjwvcGF0aD48L3N2Zz4=) !important;
      }
      .vaadin-grid-sidebar-button:after {
        content: url(data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjMDAwMDAwIiBoZWlnaHQ9IjI0IiB2aWV3Qm94PSIwIDAgMjQgMjQiIHdpZHRoPSIyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4gICAgPHBhdGggZD0iTTEwIDE4aDVWNWgtNXYxM3ptLTYgMGg1VjVINHYxM3pNMTYgNXYxM2g1VjVoLTV6Ii8+ICAgIDxwYXRoIGQ9Ik0wIDBoMjR2MjRIMHoiIGZpbGw9Im5vbmUiLz48L3N2Zz4=) !important;
      }
      .vaadin-grid-sidebar-content::content span:before {
        content: url(data:image/svg+xml;base64,PHN2ZyBmaWxsPSIjMDAwMDAwIiBoZWlnaHQ9IjI0IiB2aWV3Qm94PSIwIDAgMjQgMjQiIHdpZHRoPSIyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4gICAgPHBhdGggZD0iTTAgMGgyNHYyNEgweiIgZmlsbD0ibm9uZSIvPiAgICA8cGF0aCBkPSJNOSAxNi4xN0w0LjgzIDEybC0xLjQyIDEuNDFMOSAxOSAyMSA3bC0xLjQxLTEuNDF6Ii8+PC9zdmc+) !important;
      }
```
