### ISSUE TITLE
Images for sort icons should be customizable

### ISSUE THREAD

**Issue by kito99** [vaadin/vaadin-grid#373]
There should be custom properties exposed for sort-asc, (neutral;unsorted), and sort-desc.

**Comment by Saulis** [comment]
Thanks for the suggestion!

For a workaround, the icons can be currently customized to some extent (in Shady DOM) using selectors like:

```css
    vaadin-grid th.sort-asc:after {
      content: url('https://raw.githubusercontent.com/vaadin/vaadin-icons-files/master/png/arrow-circle-down.png') !important;
    }

    vaadin-grid th.sort-desc:after {
      content: url('https://raw.githubusercontent.com/vaadin/vaadin-icons-files/master/png/arrow-circle-up.png') !important;
    }

```
