### ISSUE TITLE
rowClassGenerator doesn't apply the given row stylings 

### ISSUE THREAD

**Issue by flashback2k14** [vaadin/vaadin-grid#374]
hey i have the follwing markup:

```html
<vaadin-grid id="gridWochenzeiten" class="style-grid" selection-mode="single">
            <table>
              <colgroup>
                <col name="Tag" width="70"/>
                <col name="Datum" width="90"/>
                <col name="ProduktivStunden" width="75"/>
                <col name="NichtProduktiveStunde" width="75"/>
                <col name="GesamtStunden" width="75"/>
                <col name="Mengeneinheit" width="75"/>
              </colgroup>
              <thead>
                <tr>
                  <th>Tag</th>
                  <th>Datum</th>
                  <th>IST(PRO)</th>
                  <th>IST(NPR)</th>
                  <th>IST(GES)</th>
                  <th>ME</th>
                </tr>
              </thead>
            </table>
          </vaadin-grid>
```

and this js code:

```javascript
// color weekend rows red
        this._grid.rowClassGenerator = function(row) {
          var wochentag = row.data.Tag;
          if (wochentag === "Sa" || wochentag === "So") {
            return "style-weekend-row";
          }
          return "style-week-row";
        };
```

and the css:

```css
.style-week-row {
        color: var(--primary-text-color, #000000);
      }
      .style-weekend-row {
        color: var(--light-accent-color, #ff0000);
      }
```

i have no clue what's wrong with this. i use v1.1.0-beta3.

**Comment by Saulis** [comment]
Are you using native Shadow or Shady DOM?

**Comment by flashback2k14** [comment]
i'm using chrome 51.0.2704.63 m and polymer 1.4. i think it's shady dom.

**Comment by tehapo** [comment]
I think you need to use a more specific selector. Try with the following selectors:
```css
.style-week-row td span {
  color: var(--primary-text-color, #000000);
}
.style-weekend-row td span {
  color: var(--light-accent-color, #ff0000);
}
```

**Comment by flashback2k14** [comment]
good idea, but it doesn't work. you can see that the styling is set, but doesn't rendered.

![markup](https://cloud.githubusercontent.com/assets/6609359/15602031/226a8382-23f3-11e6-8ab0-c354e27795fb.png)
![view](https://cloud.githubusercontent.com/assets/6609359/15602034/25ae2b52-23f3-11e6-979f-9e0c9c8d8260.png)

**Comment by tehapo** [comment]
No need to add the `td span` part to the return value of the `rowClassGenerator`. You should just add the selectors to the CSS styles in order to target the `span` element inside the cell.

**Comment by flashback2k14** [comment]
i have removed it, but still not working.

i have played a little bit and i think the problem is that the table row use classes and the style attribute. if i manually modify the markup inside the style attribute, than the color is right.

![markup2](https://cloud.githubusercontent.com/assets/6609359/15603115/47305920-23f9-11e6-8f7e-4fb3b92dd7de.png)
![view2](https://cloud.githubusercontent.com/assets/6609359/15603117/48e98f02-23f9-11e6-817e-6f3f736e1a13.png)

**Comment by flashback2k14** [comment]
here is my workaround:

```javascript
this._grid.rowClassGenerator = function(row) {
          var wochentag = row.data.Tag;
          if (wochentag === "Sa" || wochentag === "So") {
            return row.element.style.color = "red";
            // return "style-weekend-row";
          }
          return row.element.style.color = "black";
          // return "style-week-row";
        };
```

**Comment by tehapo** [comment]
Oh, now I see the problem. The styles are actually scoped and if you want to use the class name you need to target the row using the `::content` pseudo-element.

```css
vaadin-grid ::content .style-week-row {
  color: blue;
}
```
