### ISSUE TITLE
Styling row details does not work as documented

### ISSUE THREAD

**Issue by bennypowers** [vaadin/vaadin-grid#530]
When applying styles as documented to the detail row: 
```css
vaadin-grid .details {
        flex-flow: row wrap;
        padding-left: 56px !important;
      }
      vaadin-grid .details .title {
        font-weight: bolder;
      }
```
in the same scope as `vaadin-grid`, styles are not applied to the detail row.
