### ISSUE TITLE
--vaadin-grid mixins leak into row-details nested component (v2.0.0-alpha2)

### ISSUE THREAD

**Issue by pdesjardins90** [vaadin/vaadin-grid#761]
I have a ````<index-page>```` component including a grid with a row-details like this:
````html
<template class="row-details">
  <show-page></show-page>
</template>
````
The ````<show-page>```` also has a grid, and define its own styles using --vaadin-grid mixins, but the ````<index-page>````'s --vaadin-grid mixins styles leak into <show-page> and overrides them. 

index-page styles:
````css
vaadin-grid {
        background-color: #FFFFFF;
        margin-bottom: 64px;
        height: auto;

        --vaadin-grid-header-cell: {
          padding: 20px;
          height: 50px;
          font-size: 13px;
          font-weight: 500;
          line-height: 22px;
          color: rgba(0,0,0,0.54);
        };

        --vaadin-grid-body-cell: {
          padding: 20px;
          height: 53px;
          line-height: 20px;
          font-size: 14px;
          color: rgba(0,0,0,0.87);
        };

        --vaadin-grid-footer-cell: {
          padding: 20px;
          height: 50px;
          font-size: 13px;
          font-weight: 500;
          color: rgba(0,0,0,0.54);
          border-top: 1px solid #dbdbdb;
          display: flex;
          flex-direction: row;
          justify-content: flex-end;
          align-items: center;
        };

        --vaadin-grid-body-row-hover-cell: {
          background-color: red;
        };

        --vaadin-grid-body-row-selected-cell: {
          display: none;
        };

        --vaadin-grid-body-row-details-cell: {
          height: auto;
        };
      }
````
show-page styles:
````css
vaadin-grid {
        height: auto;

        --vaadin-grid-header-cell: {
          height: 50px;
          padding: 20px;
          font-size: 16px;
          font-weight: 500;
          line-height: 22px;
          color: rgba(0,0,0,0.54);
        };

        --vaadin-grid-body-cell: {
          height: 53px;
          padding: 20px;
          line-height: 20px;
          font-size: 18px;
          color: rgba(0,0,0,0.87);
        };

        --vaadin-grid-body-row-hover-cell: {
          background-color: #EBEBEB;
        };
      }
````

Why is the style not correctly encapsulated in ````<index-page>````'s local dom?
