### ISSUE TITLE
Question : How to auto adjust Height of entire grid?

### ISSUE THREAD

**Issue by atifwaqar** [vaadin/vaadin-grid#786]
I have tried `<vaadin-grid style="height:auto" ...>` but it doesnt work.

Version 2.0

**Comment by manolo** [comment]
You have to set the height of the container, then set the height of the grid to 100%

**Comment by atifwaqar** [comment]
But this way my grid size will be dependent on container right?

**Comment by jouni** [comment]
Should work already. See this example: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha3/demo/data.html#dynamic-height

**Comment by diegocerdan** [comment]
When I set height to auto to get table bigger than the viewport I can't scroll using the mouse wheel. But I can still scroll by dragging the scroll bar. Is vaading grid catching the scroll action and preventing the browser default of scrolling the window?

![image](https://cloud.githubusercontent.com/assets/1403537/23735190/09a81070-047c-11e7-8773-85f557248fb1.png)

**Comment by jouni** [comment]
First, make sure to update to 2.0.0-alpha3.

So you’re using Chrome on Windows, right?

**Comment by jouni** [comment]
Also, what other elements are you using on the page? Are you using some app-header-layout for example? Is the body element the one that scrolls?

**Comment by diegocerdan** [comment]
I was using _vaadin-grid.git#2.0-dev_ but swiched to _vaadin-grid.git#2.0.0-alpha3_.

Removed all other polymer elements to try to isolate the problem.

The scroll doesn't work if I use the CSS:
`vaadin-grid { height: auto; }`

But works fine with a fixed height like:
`vaadin-grid { height: 500px; }`

I setup a ngrok tunnel to my development http server:
http://ee353d7d.ngrok.io/

Both behaviours can be tested using Chrome DevTools to change the CSS.

**Comment by atifwaqar** [comment]
I have the same behavior as @diegocerdan

**Comment by tomivirkki** [comment]
Hi @diegocerdan,
Grid with `height: auto;` isn’t supposed to scroll (its content defines the grid height). Your layout can be fixed by applying `height: 100%` to the following:
- `<html>`
- `<body>`
- `<my-app>`
- `<twitter-dashboard>`
- and finally `<vaadin-grid>`

Does this fix the problem?

**Comment by diegocerdan** [comment]
Hi @tomivirkki,
Thanks for the tip! Applying `height: auto;` to all elements allows `<vaadin-grid>` to have his own scroller. 

Is there no way to easily make `<vaadin-grid>` scrolling agnostic and let the browser do the job? I guess is a very common scenario when using tables.

**Comment by diegocerdan** [comment]
I used the workaround suggested by @Saulis at #336.

```
// for desktop users
grid.addEventListener('mousewheel', function(e) {
  e.stopPropagation();
}, true);

// for touch device users, might have unexpected side-effects.
grid.addEventListener('touchmove', function(e) {
   e.stopPropagation();
}, true);
```
And it works. It somehow feels much snappier that letting `<vaadin-grid> ` do the scrolling job.

**Comment by jouni** [comment]
I inspected the DOM from the link you posted in #798, and the computed height of you whole document body element is over 8,000 pixels. This is of course caused by the fact that vaadin-grid has an undefined/auto height, and all the row elements are rendered in the DOM (173 rows).

It seems you already have everything else set up nicely in your stylesheet, but the `<html>` element needs `height: 100%;` to make all other elements size nicely. This should also cause vaadin-grid to only render around 40 rows, and improve the rendering performance.

**Comment by jouni** [comment]
> And it works. It somehow feels much snappier that letting <vaadin-grid> do the scrolling job.

For the amount of data you current have (173 items), scrolling the body probably performs better than vaadin-grid’s internal scrolling. But once you start having over a few hundred of items, the rendering time of the grid will start to weight more than any scrolling performance gains you might get from rendering all the rows all the time. So relying on the DOM element recycling of vaadin-grid will benefit you in those cases.

And we do still have some performance improvement options in our backlog we want to try, to make the scrolling smoother. One of them will be prototyped in #710.

**Comment by atifwaqar** [comment]
For me the issue is still there. This is how the grid looks for me : 
![image](https://cloud.githubusercontent.com/assets/4388707/24424053/7f756824-13ff-11e7-9860-afc79508fdde.png)

and here is my css : 
```css
vaadin-grid#transparent-header {
	height: auto;
	font: 500 17px "Open Sans", sans-serif;
	color: rgb(148, 154, 171);
	--divider-color: rgb(223, 232, 239);
	--vaadin-grid-cell: {
		padding: 0 13px;
	};

	--vaadin-grid-body-cell: {
		height: 80px;
	};

	--vaadin-grid-header-cell: {
		background: rgba(235, 238, 246, 0.9);
		border-bottom: 1px solid rgba(208, 217, 225, 0.9);
		border-top: 1px solid rgba(248, 250, 252, 0.9);
		min-height: 55px;
		background-image: linear-gradient(rgba(108, 160, 218, 0), rgba(108, 160, 218, 0.15));
		background-size: 1px 100%;
		background-position: 100% 0%;
		background-repeat: no-repeat;
	};

	--vaadin-grid-body-row-selected-cell: {
		background-color: rgb(131, 183, 236);
		color: #fff;
		border-bottom-color: rgb(108, 160, 218);
	};
		--vaadin-grid-body-row-odd-cell: {
		background-color: rgb(251, 252, 254);
	};
		--vaadin-grid-body-row-hover-cell: {
		background-color: rgb(235, 238, 246);
	};
		--vaadin-grid-column-resize-handle: {
		opacity: 0;
	};
};

img {
border-radius: 50%;
height: 32px;
width: 32px;
}
```

and my vaadin grid code looks like this:
```html
<datetime-picker value="{{value1}}" date-string="{{model.Dated$}}" min-date="{{starttime}}" position="bottom" use-not-native></datetime-picker>
<vaadin-grid id="transparent-header" items="[[model.Emails]]" selected-items="{{selectedItems}}">
	<vaadin-grid-column>
		<template class="header">
			<vaadin-grid-sorter path="Name">
				Type
			</vaadin-grid-sorter>
		</template>
		<template>
			<div class="capitalized">[[item.Name]]</div>
		</template>
	</vaadin-grid-column>


	<vaadin-grid-column>
		<template class="header">
			<vaadin-grid-sorter path="Subject">
				<vaadin-grid-filter path="Subject" value="[[_filterSubject]]">
					<input placeholder="Subject" value="{{_filterSubject::input}}" focus-target style="color:black">
				</vaadin-grid-filter>
			</vaadin-grid-sorter>
		</template>
		<template>
			<div class="capitalized">[[item.Subject]]</div>
		</template>
	</vaadin-grid-column>

	
	<vaadin-grid-column>
		<template class="header">
			<vaadin-grid-sorter path="ToEmail">
				<vaadin-grid-filter path="ToEmail" value="[[_filterToEmail]]">
					<input placeholder="ToEmail" value="{{_filterToEmail::input}}" focus-target style="color:black">
				</vaadin-grid-filter>
			</vaadin-grid-sorter>
		</template>
		<template>
			<div class="capitalized">[[item.ToEmail]]</div>
		</template>
	</vaadin-grid-column>
	
	<vaadin-grid-column>
		<template class="header">
			<vaadin-grid-sorter path="ccEmails">
				<vaadin-grid-filter path="ccEmails" value="[[_filterccEmails]]">
					<input placeholder="ccEmails" value="{{_filterccEmails::input}}" focus-target style="color:black">
				</vaadin-grid-filter>
			</vaadin-grid-sorter>
		</template>
		<template>
			<div class="capitalized">[[item.ccEmails]]</div>
		</template>
	</vaadin-grid-column>
	
	<vaadin-grid-column>
		<template class="header">
			<vaadin-grid-sorter path="Dated">
				Dated
			</vaadin-grid-sorter>
		</template>
		<template>
			<div class="capitalized">[[item.Dated]]</div>
		</template>
	</vaadin-grid-column>
</vaadin-grid>
```

What am I doing wrong here?

**Comment by jouni** [comment]
@atifwaqar can you explain your problem in more detail? What are you expecting, and what is actually happening? How many items do you have in your `model.Emails` array?

**Comment by atifwaqar** [comment]
@jouni 
In my attached image you can see that VaadinGrid have a right scrolbar, and that scroll bar is exactly the size of Header: 
![header](https://cloud.githubusercontent.com/assets/4388707/24541500/ffd309c8-15f7-11e7-8823-7e68534ea22b.png)


If I remove the header, the right scroll bar disappears, so to me it looks like Header is creating some issue.

> How many items do you have in your model.Emails array?

There are 10 items in `model.Emails` array.

**Comment by atifwaqar** [comment]
@jouni If you want to investigate, I can share a link to my dashboard and a login for you to test. I'll be needing your email to share the link and credentials

**Comment by jouni** [comment]
> In my attached image you can see that VaadinGrid have a right scrolbar, and that scroll bar is exactly the size of Header:
header
>
> If I remove the header, the right scroll bar disappears, so to me it looks like Header is creating some issue.

The header should not be an issue. Maybe the height of your grid/viewport is just enough to fit the 10 items in the grid, but when you have the header, the rows overflow vertically and you get a scrollbar?

> If you want to investigate, I can share a link to my dashboard and a login for you to test. I'll be needing your email to share the link and credentials

Sure, send me link to jouni@vaadin.com

**Comment by atifwaqar** [comment]
I just sent you an email.

**Comment by atifwaqar** [comment]
When you are logged in, do try to zoom out as well. 
![image](https://cloud.githubusercontent.com/assets/4388707/24546929/be111c08-160d-11e7-80d5-0e33ab04118e.png)

**Comment by jouni** [comment]
Thanks for the test case, found the issue:

It’s bootstrap.css, which resets all elements to `box-sizing: border-box`. We expect one of the internal table elements (`tbody#items` to be exact) to have `box-sizing: content-box`. This should only affect browsers without native shadow DOM support.

As a workaround, add the following to your stylesheet:

```css
vaadin-grid tbody#items {
  box-sizing: content-box;
}
```

We should fix this by explicitly setting that in the vaadin-grid styles.
