### ISSUE TITLE
Ensure vaadin-grid-table uses border-box

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#864]
Some CSS libraries, such as Bootstrap, use a global `* { box-sizing: border-box; }` style rule, which messes up the computation of the `vaadin-grid-table` element in Shady DOM, which assumes the default `content-box` sizing.

**Comment by jouni** [comment]
As a workaround, you can add the following to your app styles, after the offending global styles:

```css
vaadin-grid table {
  box-sizing: content-box;
}
```
