### ISSUE TITLE
Body cells rendering bug when using 'rem' units for padding

### ISSUE THREAD

**Issue by pdesjardins90** [vaadin/vaadin-grid#884]
When setting body cells padding with 'px' units, everything works as expected. But when setting the padding with rem units, the body cell dividers are hidden.

e.g.:

This works ok:
```css
    --vaadin-grid-body-cell: {
      padding: 20px;
    };
```

This hides the dividers:
```css
  html {
    font-size: 16px;
  }

  --vaadin-grid-body-cell: {
    padding: 1.2rem;
  };
```
